### ISSUE TITLE
Add viewport meta tag on purecss:install

### ISSUE THREAD

**Issue by rbarisic** [mseri/rails-purecss#6]
The Purecss.io website states that you need to add the viewport meta tag to your HEAD, like this:

<meta name="viewport" content="width=device-width, initial-scale=1">

could this be integrated into the command "rails g purecss:install" ?
It can be a real bummer.

Thanks.

http://purecss.io/start/#add-the-viewport-meta-element

**Comment by mseri** [comment]
Thanks for pointing it out. I've added it as an option
